version: '3.8'
services:
  jasper_report:
    #image: oraclelinux:10
    build: .
    container_name: jasper_report
    restart: unless-stopped
    # Conecta directamente con tus interfaces físicas
    #network_mode: host
    ports:
      - "8880:8080"
      - "88:80"
      #- "5505:5005" #puerto para realizar debug sobre Servlet
    privileged: true # Evita bloqueos de AppArmor al apagar o usar herramientas de red
    # Permisos específicos para nmap y herramientas de red
    cap_add:
      - NET_ADMIN
      - NET_RAW
    security_opt:
      - apparmor:unconfined # Desbloquea el cierre del contenedor desde el host
    tty: true
    stdin_open: true
    volumes:
      - ./jasper-servlet:/opt/jasper-servlet
      - ./tomcat-config/:/opt/tomcat-config
      - ./jrxml/:/usr/share/tomcat/webapps/reportes
      - ./generacion-reporte/:/vhosts/reportes
networks:
  # Solo dejamos una red interna para las víctimas de contenedor
  lab_red:
    driver: bridge
    #ipam:
    #config:
    #- subnet: 172.20.0.0/24