# Archivo de configuracion de Tomcat
# /etc/tomcat/tomcat.conf

# Donde reside la JVM
JAVA_HOME="/usr/lib/jvm/temurin-17-jdk"

# Opciones de la JVM (Memoria, etc.)
JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom -Xms512m -Xmx1024m"

# Directorios de Tomcat
CATALINA_BASE="/usr/share/tomcat"
CATALINA_HOME="/usr/share/tomcat"
JASPER_HOME="/usr/share/tomcat"
CATALINA_TMPDIR="/var/cache/tomcat/temp"

# Usuario que ejecuta Tomcat
TOMCAT_USER="tomcat"

# Seguridad
SECURITY_MANAGER="false"
